### ISSUE TITLE
Possiblity to use existing blast database

### ISSUE THREAD

**Issue by bejo-dionnez** [mrb20045/CaSilico#1]
We are very happy with your tool. It was easy to use with the examples provided. It was also very fast with the offline offtarget analysis with the blast database.

I was wondering if it is possible to define an existing blast database to make the tool even faster (no need to build the database)? When I use the LocalFasta option and define a reference which has a blast database it does not try to use this database. 

Thanks in advance!

**Comment by mrb20045** [comment]
Unfortunately it is not possible at the moment. But it took a few minutes to index a fasta file (based on your PC config as well as size of the fasta file).

Currently, we are developing the software to support more features and try to consider this point in the next version. Let me know if you need more information.

Kind regards

**Comment by bejo-dionnez** [comment]
Thank you for your reply! No problem. 
Great that you are working on more features.
